server:
  port: 9880
zuul:
  SimpleHostRoutingFilter.route.disable: true
  FormBodyWrapperFilter.pre.disable: true
  routes:
    service-a:
      path: /service-a/**
      url: https://github.com/shengnian/spring-cloud-zuul
#  routes:
#    service-a:
#      path: /service-a/**
#      serviceId: serviceA
#    service-b:
#      path: /service-b/**
#      serviceId: serviceB

#serverA:
#  ribbon:
#    listOfServers: www.google.com
#serviceB:
#  ribbon:
#    listOfServers: www.yandex.com
#
#ribbon:
#  eureka:
#    enabled: false
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true